version: '3'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    container_name: my-redis
    restart: always

  minio:
    image: quay.io/minio/minio
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    network_mode: bridge

volumes:
  minio_data:
